title: omri raccah
logo: 'https://cdn.bsky.app/img/avatar/plain/did:plc:tvtogdqxsnuqgmwvy4wognfh/bafkreicp7vpxgketucbq3tvmnhmq5jtym5cxwttlr5fwbekynheeii2d5q@jpeg'
show_downloads: false
description: postdoctoral researcher, yale university
theme: jekyll-theme-minimal
markdown: kramdown
