title: Omri Raccah
logo: 'https://cdn.bsky.app/img/avatar/plain/did:plc:tvtogdqxsnuqgmwvy4wognfh/bafkreicp7vpxgketucbq3tvmnhmq5jtym5cxwttlr5fwbekynheeii2d5q@jpeg'
show_downloads: false
description: Postdoctoral Fellow, Yale University
theme: jekyll-theme-minimal
markdown: kramdown
